//
// Created by bigna on 9/21/2025.
//

#ifndef PROJECT_1_IMAGE_PROCESSING_NAPCIO_TGACONTAINER_HPP
#define PROJECT_1_IMAGE_PROCESSING_NAPCIO_TGACONTAINER_HPP


class TgaContainer
{
};


#endif //PROJECT_1_IMAGE_PROCESSING_NAPCIO_TGACONTAINER_HPP